# Generated by Django 3.0 on 2020-11-11 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='номер маршрута')),
            ],
            options={
                'verbose_name': 'номер маршрута',
                'verbose_name_plural': 'номера маршрутов',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='вид транспорта')),
            ],
            options={
                'verbose_name': 'Вид транспорта',
                'verbose_name_plural': 'Виды транспорта',
            },
        ),
        migrations.CreateModel(
            name='OperationJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='время заявки')),
                ('from_who', models.CharField(default='', max_length=250, verbose_name='от кого')),
                ('description', models.TextField(default='', verbose_name='заявка')),
                ('brigade', models.CharField(default='', max_length=50, verbose_name='бригада')),
                ('num_car', models.CharField(default='', max_length=20, verbose_name='номер машины')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arm.Route', verbose_name='номер маршрута')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arm.Transport', verbose_name='вид транспорта')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
            },
        ),
    ]
