# Generated by Django 3.0 on 2020-11-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OperationJournal',
            new_name='Record',
        ),
    ]
