# Generated by Django 3.0 on 2020-11-12 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0002_auto_20201111_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ф.И.О. бригадира')),
            ],
            options={
                'verbose_name': 'бригада',
                'verbose_name_plural': 'бригады',
            },
        ),
        migrations.AddField(
            model_name='record',
            name='note',
            field=models.TextField(default='', verbose_name='примечание'),
        ),
        migrations.AlterField(
            model_name='record',
            name='num_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arm.NumCar', verbose_name='номер машины'),
        ),
    ]
